spring.application.name=tienda
server.port = 80


logging.pattern.dateformat = hh:mm


spring.main.banner-mode=off
#en desarrollo deshabilitamops el cache en produccion es true
spring.thymeleaf.cache=true


